### ISSUE TITLE
SVG custom font

### ISSUE THREAD

**Issue by foozzi** [libvips/pyvips#370]
```python
import pyvips

image = pyvips.Image.new_from_file('./cvp.svg')

image.write_to_file('foo.png')
```

SVG file has some css:
```css
@font-face {
    font-family: Delicious;
    src: url('./assets/fonts/Fira/Fira.ttf');
  }
```

It doesn't work with libpvips?
